### ISSUE TITLE
Purple text and icons in the dark theme look unreadable

### ISSUE THREAD

**Issue by sergd88** [ShortDevelopment/Nearby-Sharing-Windows#54] opened 2023-02-13 10:17 UTC
Purple text and icons in the dark theme look unreadable.

![Screenshot_20230213-114859__01](https://user-images.githubusercontent.com/125032334/218431245-6858d628-3aaa-4752-b51c-5bfa6ebd1505.jpg)

**Comment by ShortDevelopment** [comment] 2023-02-13 10:26
Duplicate of #38

**Closed by ShortDevelopment** 2023-02-13 10:26 UTC
Labels: bug, UI
